Letter/Controllers/BasicDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using DAL;

namespace Letter.Controllers
{
    public class BasicDataController : BaseController
    {
        #region 片区/乡镇管理
        public ActionResult RegionData()
        {
            return View();
        }

        [HttpPost] //获取片区/乡镇数据
        public ActionResult GetRegion(int pageindex, int pagesize)
        {
            var temp = db.t_County.Where(n=>n.Status == 0)
                            .OrderByDescending(n=>n.CountyId)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();

            ViewData["total"] = db.t_County.Where(n=>n.Status==0).Count();
            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("RegionPartial", temp);
        }

        [HttpPost] //添加片区/乡镇数据
        public ActionResult AddRegion(CountyModel model)
        {
            t_County newCounty = new t_County();
            newCounty.CountyName = model.CountyName.Trim();
            db.t_County.Add(newCounty);

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "添加成功"));
            }
            catch(Exception)
            {
                return Json(new MessageData(false, "添加失败"));
            }

            
        }

        [HttpPost] //修改片区/乡镇数据
        public ActionResult EditRegion(CountyModel model)
        {
            var newCounty = db.t_County.FirstOrDefault(n => n.CountyId == model.ID);
            newCounty.CountyName = model.CountyName.Trim();

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "修改成功"));
            }
            catch (Exception)
            {
                return Json(new MessageData(false, "修改失败"));
            }


        }

        [HttpPost] //删除片区/乡镇数据
        public ActionResult DelRegion(int id)
        {
            var queryCaseInfo = db.t_CaseInfo.Where(n => n.TownshipType == id && n.IsDelete == 0).ToList();
            if (queryCaseInfo.Count == 0)
            {
                var newCounty = db.t_County.FirstOrDefault(n => n.CountyId == id);
                newCounty.Status = 1;

                try
                {
                    db.SaveChanges();
                    return Json(new MessageData(true, "删除成功"));
                }
                catch (Exception)
                {
                    return Json(new MessageData(false, "删除失败"));
                }
            }
            else
            {
                return Json(new MessageData(false, "已有案件关联此稳控单位，无法删除"));
            }
            


        }
        #endregion

        #region 党政领导信息管理
        public ActionResult LeaderData()
        {
            return View();
        }

        [HttpPost] //获取领导信息
        public ActionResult GetLeader(int pageindex, int pagesize)
        {
            var temp = db.t_Leader.Where(n => n.Status == 0)
                            .OrderByDescending(n => n.LeaderId)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();

            ViewData["total"] = db.t_Leader.Where(n => n.Status == 0).Count();
            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("LeaderPartial", temp);
        }

        [HttpPost] //查询领导信息
        public ActionResult QueryLeader(int pageindex, int pagesize,string leaderName, string postion)
        {
            var queryList = db.t_Leader.Where(n => n.LeaderName.Contains(leaderName) && n.LeaderPosition.Contains(postion) && n.Status == 0)
                            .OrderByDescending(n => n.LeaderId)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();

            ViewData["total"] = db.t_Leader.Where(n => n.LeaderName.Contains(leaderName) && n.LeaderPosition.Contains(postion) && n.Status == 0).Count();
            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("LeaderPartial", queryList);
        }

        [HttpPost] //添加领导信息
        public ActionResult AddLeader(LeaderModel model)
        {
            t_Leader newLeader = new t_Leader();
            newLeader.LeaderName = model.LeaderName.Trim();
            newLeader.LeaderSex = model.LeaderSex;
            newLeader.LeaderPosition = model.LeaderPostion.Trim();
            newLeader.Remark = model.Remark;

            db.t_Leader.Add(newLeader);

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "添加成功"));
            }
            catch (Exception e)
            {
                return Json(new MessageData(false, "添加失败"));
            }
        }

        [HttpPost] //修改领导信息
        public ActionResult EditLeader(LeaderModel model)
        {
            var newLeader = db.t_Leader.FirstOrDefault(n => n.LeaderId == model.ID);
            newLeader.LeaderName = model.LeaderName.Trim();
            newLeader.LeaderSex = model.LeaderSex.Trim();
            newLeader.LeaderPosition = model.LeaderPostion.Trim();
            newLeader.Remark = model.Remark;

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "修改成功"));
            }
            catch (Exception)
            {
                return Json(new MessageData(false, "修改失败"));
            }
        }

        [HttpPost] //删除领导信息
        public ActionResult DelLeader(int id)
        {
            var newLeader = db.t_Leader.FirstOrDefault(n => n.LeaderId == id);
            newLeader.Status = 1;
            var queryLeader = db.t_LeaderMeeting.Where(n => n.LeaderID == id && n.IsDelete == 0).ToList();
            if (queryLeader.Count == 0)
            {
                try
                {
                    db.SaveChanges();
                    return Json(new MessageData(true, "删除成功"));
                }
                catch (Exception)
                {
                    return Json(new MessageData(false, "删除失败"));
                }
            }
            else
            {
                return Json(new MessageData(false, "该领导已有接访记录，无法删除"));
            }
        }
        #endregion

        #region 责任单位
        public ActionResult CompanyData()
        {
            return View();
        }

        [HttpPost] //获取责任单位数据
        public ActionResult GetCompany(int pageindex, int pagesize)
        {
            var temp = db.t_Responsibility.Where(n => n.Status == 0)
                            .OrderByDescending(n => n.TableId)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();

            ViewData["total"] = db.t_Responsibility.Where(n => n.Status == 0).Count();
            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("CompanyPartial", temp);
        }

        [HttpPost] //添加责任单位数据
        public ActionResult AddCompany(CompanyModel model)
        {
            t_Responsibility newCompany = new t_Responsibility();
            newCompany.UnitName = model.UnitName.Trim();
            db.t_Responsibility.Add(newCompany);

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "添加成功"));
            }
            catch (Exception e)
            {
                return Json(new MessageData(false, "添加失败："+e.Message));
            }
        }

        [HttpPost] //修改责任单位数据
        public ActionResult EditCompany(CompanyModel model)
        {
            var newCompany = db.t_Responsibility.FirstOrDefault(n => n.TableId == model.ID);
            newCompany.UnitName = model.UnitName.Trim();

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "修改成功"));
            }
            catch (Exception)
            {
                return Json(new MessageData(false, "修改失败"));
            }
        }

        [HttpPost] //删除责任单位数据
        public ActionResult DelCompany(int id)
        {
            var queryCaseInfo = db.t_CaseInfo.Where(n => n.UnitType == id && n.IsDelete == 0).ToList();
            if (queryCaseInfo.Count == 0)
            {
                var newCompany = db.t_Responsibility.FirstOrDefault(n => n.TableId == id);
                newCompany.Status = 1;

                try
                {
                    db.SaveChanges();
                    return Json(new MessageData(true, "删除成功"));
                }
                catch (Exception)
                {
                    return Json(new MessageData(false, "删除失败"));
                }
            }
            else
            {
                return Json(new MessageData(false, "已有案件关联此责任单位，无法删除"));
            }
        }
        #endregion
    }
}

Letter/Views/BasicData/CompanyData.cshtml
@using Model
@model CompanyModel
@{
    ViewBag.Title = "RegionData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="headline">责任单位管理</h2>

<div class="row-fluid">
        <div class="span12">
            <div class="x_panel">
                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal" onclick="AddModal()">新增责任单位</button>
                <div class="x_content">

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>序号</th>
                                <th>责任单位</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody id="tbodystr"></tbody>
                    </table>
                    <div id="data-pager">
                        
                    </div>

                </div>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            @using (Html.BeginForm("", "", FormMethod.Post, new { @class = "form-label-left", @Id = "demoForm" }))
            {
                <div class="modal-body">
                    <div class="form-group hidden">
                        <label for="ID" class="col-sm-3 control-label">ID</label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(n => n.ID, new { @Id = "ID", @class = "demoForm" })
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span3 offset1">
                            <label for="Name" class="control-label text-center"><span class="required">*</span>责任单位名称</label>
                        </div>

                        <div class="span6">
                            @Html.TextBoxFor(n => n.UnitName, new { @Id = "Name", @class = "form-control", @required = "required", @placeholder = "请输入责任单位名称" })
                        </div>
                    </div>
                </div>
                <input class="hidden" value="0" data-parsley-checkdelaytime />
                <div class="modal-footer">
                    <input id="status" class="hidden" />
                    <button class="btn btn-primary" onclick="return SubmitBtn()">保存</button>
                    <button type="button" class="btn btn-gray" data-dismiss="modal">关闭</button>
                </div>
            }
        </div>
    </div>
</div>





<script>
    window.Parsley
        .addValidator('checkdelaytime', {
            validateString: function (value) {
                $('#demoForm .parsley-errors-list').show();
                return true;//校验不通过,会将data-parsley-checkdelaytime-message对应的信息输出
            }
        });
    $(function () {
        createTable(1);
    })
    //数据表格
    var pagesize = 15;
    var pageindex = 1;

    function createTable(number) {
        pageindex = number;
            $.ajax({
                method: 'post',
                url: "@Url.Action("GetCompany", "BasicData")",
                data: {
                    "pageindex": pageindex,
                    "pagesize": pagesize
                    },
                cache: false,
                async: true,
                crossDomain: true,
                timeout: 20000,
                success: function (data) {
                    //$('#tbodystr').empty();
                    $('#tbodystr').empty().html(data);
                    if ($('#total').text() == 0) {
                        $('#tbodystr').empty().append('<tr><td colspan="3">暂无信息</td></tr>')
                        $('#data-pager').empty()
                    }
                    else {
                        var html2 = customPaging(pageindex, pagesize, $('#total').text());
                        $('#data-pager').empty().append(html2);
                    }
                  
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $('#tbodystr').empty().append('<tr><td colspan="7">抱歉，出了点意外状况</td></tr>');
                    $('#data-pager').empty();
                    //closeLoading();
                }
            });
    }
    function SubmitBtn() {
        if ($('#demoForm').parsley().isValid()) {
            var status = $('#status').val();
            if (status == 1)
            {
                //修改
                $.ajax({
                    method: 'post',
                    cache:false,
                    async: false,
                    url:"@Url.Action("EditCompany", "BasicData")",
                    data: $('#demoForm').serialize(),// 你的formid
                    error: function(request) {
                        alert("Connection error");
                    },
                    success: function (data) {
                        $("#myModal").modal("hide");
                        alertModal('提示！', data.Message);
                        createTable(pageNumAll);
                        @*window.location.href = "@Url.Action("RegionData", "BasicData")";*@
                    }
                });
            }
            else
            {
                //添加
                $.ajax({
                    cache: false,
                    type: "POST",
                    url:"@Url.Action("AddCompany", "BasicData")",
                    data: $('#demoForm').serialize(),// 你的formid
                    async: false,
                    error: function(request) {
                        alert("Connection error");
                    },
                    success: function (data) {
                        $("#myModal").modal("hide");
                        alertModal('提示！', data.Message);
                        createTable(pageNumAll);
                    }
                });
            }
            return false;
        }


    }
    function AddModal() {
        $('#myModalLabel').text('新增责任单位');
        $('#status').val("");
        $('#Name').val("");
        $('#demoForm .parsley-error').removeClass('parsley-error');
        $('#demoForm .parsley-errors-list').hide();
    }
    function EditModal(row) {
        $('#myModalLabel').text('修改责任单位');
        $('#status').val("1")
        $('#ID').val($("table tr:eq(" + row + ") th:eq(0)").text());
        $('#Name').val($("table tr:eq(" + row + ") td:eq(0)").text());
        $('#demoForm .parsley-error').removeClass('parsley-error');
        $('#demoForm .parsley-errors-list').hide();
    }
    function DelModal(id) {
        alertDel('提示!', '确定要删除这个责任单位吗？', "DelCompany", id);
    }

</script>

Letter/Views/BasicData/LeaderData.cshtml
@using Model
@model LeaderModel
@{
    ViewBag.Title = "党政领导信息管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="headline">党政领导信息管理</h2>
<div class="row-fluid">
        <div class="span12">
            <div class="x_panel">
                <div class="row-fluid">
                    <div class="span12" style="position:relative">
                        <div class="span6">
                            <div class="dataTables_length" id="datatable_length">
                                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal" onclick="AddModal()">录入党政领导信息</button>
                            </div>
                        </div>
                        <div class="span2" style="position:relative;z-index:1;margin-left: 8.5%;">
                            <input id="leaderName" type="text" class="span12" placeholder="姓名">
                        </div>
                        <div class="span2" style="position:relative;z-index:1;">
                            <input id="leaderPostion" type="text" class="span12 " placeholder="职务">
                        </div>
                        <div class="span2" style="position:absolute;z-index:0;right:0">
                            <button class="btn btn-primary " type="button" onclick="clearSearch()" style="float:right">清除</button>
                            <button class="btn btn-primary " type="button" onclick="search()" style="float:right">搜索</button>
                        </div>
                    </div>
                </div>

               
                <div class="x_content">

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>序号</th>
                                <th>领导姓名</th>
                                <th>性别</th>
                                <th>职务</th>
                                @*<th>联系方式</th>
                                <th>办公所在地</th>*@
                                <th>备注</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody id="tbodystr"></tbody>
                    </table>
                    <div id="data-pager">
                      
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            @using (Html.BeginForm("", "", FormMethod.Post, new { @class = " form-label-left", @Id = "demoForm" }))
    {
        <div class="modal-body">
            <div class="row-fluid hidden">
                <label for="ID" class="span3">ID</label>
                <div class="span8">
                    @Html.TextBoxFor(n => n.ID, new { @Id = "ID", @class = "span12" })
                </div>
            </div>

            <div class="row-fluid">
                <div class="span2 offset2 ">
                    <label for="Name" class="control-label "><span class="required">*</span>姓名</label>
                </div>

                <div class="span6">
                    @Html.TextBoxFor(n => n.LeaderName, new { @Id = "Name", @class = "form-control span12", @required = "required", @placeholder = "请输入领导姓名", type = "text" })
                </div>
            </div>

            <div class="row-fluid">
                <div class="span2 offset2 ">
                    <label for="Name" class="control-label ">性别</label>
                </div>

                <div class="span6">
                    <label class="span1">
                        @Html.RadioButtonFor(n => n.LeaderSex, "1")

                    </label>
                    <label class="span2">
                        男
                    </label>
                    <label class="span1">
                        @Html.RadioButtonFor(n => n.LeaderSex, "0")
                    </label>
                    <label class="span1">
                        女
                    </label>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span2 offset2 ">
                    <label for="Name" class="control-label "><span class="required">*</span>职务</label>
                </div>

                <div class="span6">
                    @Html.TextBoxFor(n => n.LeaderPostion, new { @Id = "Postion", @class = "form-control span12", @required = "required", @placeholder = "请输入领导职务" })
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2 offset2 ">
                    <label for="Name" class="control-label ">备注</label>
                </div>

                <div class="span6">
                    @Html.TextAreaFor(n => n.Remark, new { @Id = "remark", @class = "form-control span12 txt-overflow", @rows = "4" })
                </div>
            </div>

        </div>
        <input class="hidden" value="0" data-parsley-checkdelaytime />
        <div class="modal-footer">
            <input id="status" class="hidden" />
            <button class="btn btn-primary" onclick="return SubmitBtn()">保存</button>
            <button type="button" class="btn btn-gray" data-dismiss="modal">关闭</button>
        </div>
}


        </div>
    </div>
</div>


<script>
    window.Parsley
        .addValidator('checkdelaytime', {
            validateString: function (value) {
                $('#demoForm .parsley-errors-list').show();
                return true;//校验不通过,会将data-parsley-checkdelaytime-message对应的信息输出
            }
        });
    $(function () {
        createTable(1);
    })
    var pagesize = 15;
    var pageindex = 1;
    function createTable(number) {
        pageindex = number;
        var leaderName = $('#leaderName').val();
        var postion = $('#leaderPostion').val();
        if (!leaderName.length && !postion.length) {
            $.ajax({
                method: 'post',
                url: "@Url.Action("GetLeader", "BasicData")",
                data: {
                    "pageindex": pageindex,
                    "pagesize": pagesize
                },
                cache: false,
                async: true,
                crossDomain: true,
                timeout: 20000,
                success: function (data) {
                    //$('#tbodystr').empty();
                    $('#tbodystr').empty().html(data);
                    if ($('#total').text() == 0) {
                        $('#tbodystr').empty().append('<tr><td colspan="6">暂无信息</td></tr>')
                        $('#data-pager').empty()
                    }
                    else {
                        var html2 = customPaging(pageindex, pagesize, $('#total').text());
                        $('#data-pager').empty().append(html2);
                    }
                   
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $('#tbodystr').empty().append('<tr><td colspan="6">抱歉，出了点意外状况</td></tr>');
                    $('#data-pager').empty();
                    //closeLoading();
                }
            });
        }
        else
        {
            $.ajax({
                method: 'post',
                url: "@Url.Action("QueryLeader", "BasicData")",
                data: {
                    "leaderName":leaderName,
                    "postion": postion,
                    "pageindex": pageindex,
                    "pagesize": pagesize
                },
                cache: false,
                async: true,
                crossDomain: true,
                //timeout: 20000,
                success: function (data) {
                    //$('#tbodystr').empty();
                    $('#tbodystr').empty().html(data);
                    if ($('#total').text() == 0) {
                        $('#tbodystr').empty().append('<tr><td colspan="6">暂无信息</td></tr>')
                        $('#data-pager').empty()
                    }
                    else {
                        var html2 = customPaging(pageindex, pagesize, $('#total').text());
                        $('#data-pager').empty().append(html2);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $('#tbodystr').empty().append('<tr><td colspan="7">抱歉，出了点意外状况</td></tr>');
                    $('#data-pager').empty();
                    //closeLoading();
                }
            });
        }
            
    }
    function search() {
        var leaderName = $('#leaderName').val();
        var postion = $('#leaderPostion').val();

        if (leaderName.length || postion.length) {
            createTable(1);
        } else {
            createTable(1);
        }
        return false;
    }
    function SubmitBtn() {
        if ($('#demoForm').parsley().isValid()) {
            var status = $('#status').val();
            if (status == 1)
            {
                //修改
                $.ajax({
                    cache: true,
                    type: "POST",
                    url:"@Url.Action("EditLeader", "BasicData")",
                    data: $('#demoForm').serialize(),// 你的formid
                async: false,
                error: function(request) {
                    alert("Connection error");
                },
                success: function (data) {
                    $("#myModal").modal("hide");
                    alertModal('提示！', data.Message);
                    createTable(pageNumAll);
                }
                });
            }
            else
            {
                //添加
                $.ajax({
                    cache: true,
                    type: "POST",
                    url:"@Url.Action("AddLeader", "BasicData")",
                    data: $('#demoForm').serialize(),// 你的formid
                async: false,
                error: function(request) {
                    alert("Connection error");
                },
                success: function (data) {
                    $("#myModal").modal("hide");
                    alertModal('提示！', data.Message);
                    createTable(pageNumAll);
                }
            });
        }
            return false;
        }


    }
    function AddModal() {
        $('#myModalLabel').text('新增领导信息');
        $('#status').val("");
        $('#ID').val("");
        $('#Name').val("");
        $('#Postion').val("");
        $('#remark').val("");
        $('input[name="LeaderSex"][value="1"]').prop('checked', true);
        $('#demoForm .parsley-error').removeClass('parsley-error');
        $('#demoForm .parsley-errors-list').hide();
    }
    function EditModal(row) {
        $('#myModalLabel').text('修改领导信息');
        $('#status').val("1")
        $('#ID').val($("table tr:eq(" + row + ") th:eq(0)").text());
        $('#Name').val($("table tr:eq(" + row + ") td:eq(0)").text());
        $('#Postion').val($("table tr:eq(" + row + ") td:eq(2)").text());
        $('#remark').val($("table tr:eq(" + row + ") td:eq(3)").text());
        var nature = $("table tr:eq(" + row + ") th:eq(1)").text();
        switch (nature) {
            case "1":
                $('input[name="LeaderSex"][value="1"]').prop('checked', true);
                break;
            case "0":
                $('input[name="LeaderSex"][value="0"]').prop('checked', true);
                break;
        }
        $('#demoForm .parsley-error').removeClass('parsley-error');
        $('#demoForm .parsley-errors-list').hide();
    }
    function Del(id) {
        alertDel('提示!', '确定要删除这个领导吗？', "DelLeader", id);
    }
    function clearSearch() {
        $('#leaderName').val("");
        $('#leaderPostion').val("");

        createTable(1);
    }

</script>