Letter/Controllers/UpgradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using DAL;
using System.IO;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace Letter.Controllers
{
    public class UpgradeController : BaseController
    {
        public ActionResult Upgrade()
        {
            return View();
        }
        public ActionResult UpgradeList(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                ViewData["ID"] = id;
                return View();
            }
        }
        [HttpPost] //获取案件信息
        public ActionResult GetCaseInfo(int pageindex, int pagesize)
        {
            string sql = "SELECT C.ID as ID, u.CaseInfoID,c.[PetitionName],co.[CountyName],r.[UnitName], COUNT(u.CaseInfoID) as CountID FROM[LetterInfo].[dbo].[t_CaseInfo] c left join [dbo].[t_County] co on c.TownshipType = co.CountyId left join [dbo].[t_Responsibility] r on c.UnitType = r.TableId inner join [dbo].[t_Record] u on c.ID = u.CaseInfoID where c.IsDelete = 0 and u.IsDelete = 0 Group by  u.CaseInfoID,c.[PetitionName],co.[CountyName],r.[UnitName],C.ID";
            var temp = db.Database.SqlQuery<t_UpgradeList>(sql)
                            .OrderByDescending(n => n.ID)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();
            ViewData["total"] = db.Database.SqlQuery<t_UpgradeList>(sql).Count();

            return PartialView("UpgradePartial", temp);
        }
        [HttpPost] //查询信息 //int pageindex, int pagesize, string petitionName,string unitName,string countyName, string recordType, string startDate, string endDate
        public ActionResult QueryCaseInfo(string jsonStr)
        {
            JObject json = (JObject)JsonConvert.DeserializeObject(jsonStr);
            int pageindex = Convert.ToInt32(json["pageindex"].ToString());
            int pagesize = Convert.ToInt32(json["pagesize"].ToString());
            string petitionName = json["petitionName"].ToString();
            string unitName = json["unitName"].ToString();
            string countyName = json["countyName"].ToString();

            string where = string.Empty;

            if (petitionName.Trim() != "")
            {
                where += " and PetitionName like '%" + petitionName + "%'";
            }
            if (unitName.Trim() != "")
            {
                where += " and UnitName like '%" + unitName + "%'";
            }
            if (countyName.Trim() != "")
            {
                where += " and CountyName like '%" + countyName + "%'";
            }

            string sql = "SELECT u.CaseInfoID,c.[PetitionName],co.[CountyName],r.[UnitName], COUNT(u.CaseInfoID) as ID FROM[LetterInfo].[dbo].[t_CaseInfo] c left join [dbo].[t_County] co on c.TownshipType = co.CountyId left join [dbo].[t_Responsibility] r on c.UnitType = r.TableId inner join [dbo].[t_Record] u on c.ID = u.CaseInfoID where c.IsDelete = 0 and u.IsDelete = 0 "+ where + " Group by  u.CaseInfoID,c.[PetitionName],co.[CountyName],r.[UnitName]";
            var queryList = db.Database.SqlQuery<t_UpgradeList>(sql)
                            .OrderByDescending(n => n.RecordDate)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();

            ViewData["total"] = db.Database.SqlQuery<t_UpgradeList>(sql).Count();

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("UpgradePartial", queryList);
        }
        [HttpPost] //获取案件信息
        public ActionResult GetCaseInfoList(int pageindex, int pagesize, int id)
        {
            string sql = "SELECT u.ID,u.CaseInfoID,c.[AppealTitle],c.[PetitionName],co.[CountyName],r.[UnitName],u.[RecordType],u.[RecordDate],u.[RecordFileName],u.[RecordContent] FROM[LetterInfo].[dbo].[t_CaseInfo] c left join [dbo].[t_County] co on c.TownshipType = co.CountyId left join [dbo].[t_Responsibility] r on c.UnitType = r.TableId inner join [dbo].[t_Record] u on c.ID = u.CaseInfoID where c.IsDelete = 0 and u.IsDelete = 0 and u.CaseInfoID = " + id;
            var temp = db.Database.SqlQuery<t_UpgradeList>(sql)
                            .OrderByDescending(n => n.ID)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();
            ViewData["total"] = db.Database.SqlQuery<t_UpgradeList>(sql).Count();

            return PartialView("UpgradeListPartial", temp);
        }

        [HttpPost] //查询信息 //int pageindex, int pagesize, string petitionName,string unitName,string countyName, string recordType, string startDate, string endDate
        public ActionResult QueryCaseInfoList(string jsonStr)
        {
            JObject json = (JObject)JsonConvert.DeserializeObject(jsonStr);
            int id = Convert.ToInt32(json["id"].ToString());
            int pageindex = Convert.ToInt32(json["pageindex"].ToString());
            int pagesize = Convert.ToInt32(json["pagesize"].ToString());
            //string petitionName = json["petitionName"].ToString();
            //string unitName = json["unitName"].ToString();
            //string countyName = json["countyName"].ToString();
            string recordType = json["recordType"].ToString();
            string startDate = json["startDate"].ToString();
            string endDate = json["endDate"].ToString();

            string where = string.Empty;

            //if (petitionName.Trim() != "")
            //{
            //    where += " and PetitionName like '%" + petitionName + "%'";
            //}
            //if (unitName.Trim() != "")
            //{
            //    where += " and UnitName like '%" + unitName + "%'";
            //}
            //if (countyName.Trim() != "")
            //{
            //    where += " and CountyName like '%" + countyName + "%'";
            //}
            if (recordType != "99")
            {
                where += " and RecordType = " + recordType;
            }
            if (startDate != "")
            {
                where += " and RecordDate >= '" + startDate + "'";
            }
            if (endDate.Length != 0)
            {
                where += " and RecordDate <= '" + endDate + "'";
            }

            string sql = "SELECT u.ID,u.CaseInfoID,c.[AppealTitle],c.[PetitionName],co.[CountyName],r.[UnitName],u.[RecordType],u.[RecordDate],u.[RecordFileName],u.[RecordContent] FROM[LetterInfo].[dbo].[t_CaseInfo] c left join [dbo].[t_County] co on c.TownshipType = co.CountyId left join [dbo].[t_Responsibility] r on c.UnitType = r.TableId inner join [dbo].[t_Record] u on c.ID = u.CaseInfoID where c.IsDelete = 0 and u.IsDelete = 0 and u.CaseInfoID = "+ id + where;
            var queryList = db.Database.SqlQuery<t_UpgradeList>(sql)
                            .OrderByDescending(n => n.RecordDate)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();

            ViewData["total"] = db.Database.SqlQuery<t_UpgradeList>(sql).Count();

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("UpgradeListPartial", queryList);
        }

        [HttpPost] //获进京赴省记录
        public ActionResult GetUpgradeList(int pageindex, int pagesize, int id)
        {
            var temp = db.t_Record.Where(n => n.CaseInfoID == id)
                .OrderByDescending(n => n.ID)
                .Skip(pagesize * (pageindex - 1))
                .Take(pagesize).ToList();

            ViewData["total"] = db.t_Record.Where(n => n.CaseInfoID == id).Count();
            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("UpgradeDetailsPartial", temp);
        }

        [HttpPost] //查询信息
        public ActionResult QueryUpgradeList(int pageindex, int pagesize, string number, string title, int id, string recordType)
        {
            var queryList = db.t_Record.Where(n => n.t_CaseInfo.AppealNumber.Contains(number) && n.t_CaseInfo.AppealTitle.Contains(title) && n.t_CaseInfo.IsDelete == 0 && n.RecordType.Contains(recordType) && n.CaseInfoID == id)
                            .OrderByDescending(n => n.ID)
                           .Skip(pagesize * (pageindex - 1))
                           .Take(pagesize).ToList();

            ViewData["total"] = db.t_Record.Where(n => n.t_CaseInfo.AppealNumber.Contains(number) && n.t_CaseInfo.AppealTitle.Contains(title) && n.t_CaseInfo.IsDelete == 0 && n.RecordType.Contains(recordType) && n.CaseInfoID == id).Count();

            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("UpgradeDetailsPartial", queryList);
        }


        public ActionResult UpgradeDetails(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                ViewData["ID"] = id;
                return View();
            }
        }
        [HttpPost]
        public ActionResult AddUpgrader(UpgradeDetailModel model)
        {
            var caseInfoId1 = db.t_CaseInfo.Where(r => r.AppealNumber == model.AppealNumber || r.AppealTitle == model.AppealNumber).ToList();
            var caseInfoId = db.t_CaseInfo.FirstOrDefault(r => r.AppealNumber == model.AppealNumber || r.AppealTitle == model.AppealNumber).ID;
            t_Record newMeeting = new t_Record();
            newMeeting.CaseInfoID = caseInfoId;
            newMeeting.RecordType = model.RecordType.Trim();

Letter/Views/Upgrade/UpgradeDetails.cshtml
@using Model
@model UpgradeDetailModel
@{
    ViewBag.Title = "UpgradeDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int ID = ViewData.GetInt("ID");
}

<h2 class="headline">进京/赴省记录</h2>
<div class="row-fluid">
    <div class="span12">
        <div class="x_panel">
            <div class="row-fluid">
                <div class="span12" style="position:relative;z-index:1">
                    <div class="span9">
                        @*<div class="dataTables_length" id="datatable_length">
                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal" onclick="AddModal()">新增进京/赴省记录</button>
            </div>*@
                    </div>
                    @*<div class="span2 " style="position:relative;z-index:1;margin-left: 8.5%;">
                        <input id="Anumber" autocomplete="off" class="span12" type="text" data-provide="typeahead" placeholder="案件编号">
                    </div>
                    <div class="span2">
                        <input id="Atitle" type="text" class="span12 " placeholder="诉求标题">
                    </div>*@
                    <div class="span1" style="position:relative;z-index:1;margin-left: 8.5%;">
                        <select id="searchType" class="span12 form-control" required="required">
                            <option value="99">全部</option>
                            <option value="1">进京</option>
                            <option value="0">赴省</option>
                        </select>
                    </div>
                    <div class="span2" style="position:absolute;z-index:0;right:0">
                        <button class="btn btn-primary " type="button" onclick="clearSearch()" style="float:right">清除</button>
                        <button class="btn btn-primary " type="button" onclick="search()" style="float:right">搜索</button>
                    </div>
                </div>
              
            </div>

            <div class="x_content">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>类型</th>
                            <th>日期</th>
                            <th>内容</th>
                            <th>相关附件</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody id="tbodystr"></tbody>
                </table>
                <div id="data-pager">
                
                </div>
            </div>
        </div>
    </div>
</div>


<div class="clearfix"></div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">查看进京/赴省记录</h4>
            </div>
            @using (Html.BeginForm("", "", FormMethod.Post, new { @Id = "demoForm", @enctype = "multipart/form-data" }))
            {
                <div class="modal-body">
                    <div class="row-fluid">
                        <div class="form-group hidden">
                            <div class="span4">
                                <label for="ID" class="modal-label">ID</label>
                            </div>
                            <div class="span6">
                                @*@Html.TextBoxFor(n => n.UserId, new { @Id = "ID", @class = "span12" })*@
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="form-group">
                            <div class="span4">
                                <label for="selectNumber" class="modal-label">案件</label>
                            </div>
                            <div class="span6">
                                @Html.TextBoxFor(n => n.AppealNumber, new { @Id = "searchAuto", @class = "span12 form-control", autocomplete = "off", @disabled = "disabled" })
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="form-group">
                            <div class="span4">
                                <label for="RecordType" class="modal-label">类型</label>
                            </div>
                            <div class="span6">
                                <select id="RecordType" name="RecordType" class="span12 form-control" disabled="disabled">
                                    <option value="">请选择类型</option>
                                    <option value="1">进京</option>
                                    <option value="0">赴省</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="form-group">
                            <div class="span4">
                                <label for="RecordDate" class="modal-label">日期</label>
                            </div>
                            <div class="span6">
                                @Html.TextBoxFor(n => n.RecordDate, new { @id = "RecordDate", @class = "span12 jedate", @readonly = "readonly", placeholder = "年/月/日", @style = "cursor: default", @disabled = "disabled" })
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="form-group">
                            <div class="span4">
                                <label for="Comment" class="modal-label">内容</label>
                            </div>
                            <div class="span6">
                                @Html.TextAreaFor(n => n.RecordContent, new { @Id = "Comment", @class = "form-control span12 txt-overflow", @rows = "4", @disabled = "disabled" })
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="form-group">
                            <div class="span4">
                                <label for="ReceptionDate" class="modal-label">相关附件</label>
                            </div>
                            <div class="span6">
                                <label id="down" style="cursor: default"></label>
                            </div>
                        </div>
                    </div>
                </div>
                <input class="hidden" value="0" data-parsley-checkdelaytime />
                <div class="modal-footer">
                    <button type="button" class="btn btn-gray" data-dismiss="modal">关闭</button>
                </div>
            }

        </div>
    </div>
</div>


<script>
    $(function () {
        createTable(1);
    })
    var searchLen;
    var pagesize = 15;
    var pageindex = 1;

    function createTable(number) {
        pageindex = number;
        //var number = $('#Anumber').val();
        //var title = $('#Atitle').val();
        var type = $('#searchType').val();

        //type == "" ? type = 99 : type = $('#selectLeader').val();
        //!number.length && !title.length && 
        if (type==99)
        {
            $.ajax({
                method: 'post',
                url: "@Url.Action("GetUpgradeList", "Upgrade")",
                data: {
                    "id":@ID,
                    "pageindex": pageindex,
                    "pagesize": pagesize
                },
            cache: false,
            async: true,
            crossDomain: true,
            timeout: 20000,
            success: function (data) {
                //$('#tbodystr').empty();
                $('#tbodystr').empty().html(data);
                if($('#total').text() == 0){
                    $('#tbodystr').empty().append('<tr><td colspan="8">暂无信息</td></tr>')
                    $('#data-pager').empty()
                }
                else
                {
                    var html2 = customPaging(pageindex, pagesize, $('#total').text());

                    $('#data-pager').empty().append(html2);
                    $('.tdstr').each(function (i, v) {
                        var val = $(this).text()
                        //textHidden(val, 100, ".tdstr")
                        $(this).text(textHidden(val, 100, ".tdstr"))
                    });
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                $('#tbodystr').empty().append('<tr><td colspan="8">抱歉，出了点意外状况</td></tr>');
                $('#data-pager').empty();
                //closeLoading();
            }
        });
        }
        else
        {
            $.ajax({
                method: 'post',
                url: "@Url.Action("QueryUpgradeList", "Upgrade")",
                data: {
                    "pageindex": pageindex,
                    "pagesize": pagesize,
                    "number":"",
                    "title":"",
                    "id":@ID,
                    "recordType":type
                },
            cache: false,
            async: true,
            crossDomain: true,
            timeout: 20000,
            success: function (data) {
                //$('#tbodystr').empty();
                $('#tbodystr').empty().html(data);
                var total = $('#total').text();
                if (total == 0){
                    $('#tbodystr').empty().html('<tr><td colspan="8">暂无信息</td></tr>')
                    $('#data-pager').empty()
                }
                else
                {
                    var html2 = customPaging(pageindex, pagesize, $('#total').text());

                    $('#data-pager').empty().append(html2);
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                $('#tbodystr').empty().append('<tr><td colspan="8">抱歉，出了点意外状况</td></tr>');
                $('#data-pager').empty();
                //closeLoading();
            }
        });

        }


    }
    function search() {
        //var number = $('#Anumber').val();
        //var title = $('#Atitle').val();
        var type = $('#searchType').val();
        //number.length || type != "" || 
        if (type != 99) {
            createTable(1);
        } else {
            createTable(1);
        }
        return false;
    }
    function searchNum() {
        var val = $('#searchAuto').val();
        var a = $.inArray(val, searchLen);
        if (searchLen.length == 0 && a == -1) {
            $('#Num').val(0);
            $('#searchAuto').addClass("parsley-error");
            $('#parsley-id-3').show();
            $('#parsley-id-7').hide();
        } else {
            $('#searchAuto').removeClass("parsley-error");
            $('#parsley-id-3').hide();
            $('#parsley-id-7').hide();
        }
    }
 
    function SeeModal(row) {
        $('#searchAuto').val($("table tr:eq(" + row + ") th:eq(0)").text());
        $('#RecordType').find("option:selected").text($("table tr:eq(" + row + ") td:eq(0)").text());
        $('#RecordDate').val($("table tr:eq(" + row + ") td:eq(1)").text());
        $('#Comment').val($("table tr:eq(" + row + ") th:eq(1)").text());
        var html = $("table tr:eq(" + row + ") td:eq(3)").html();
        $('#down').empty().html(html);
    }


    function clearSearch() {
        //$('#Anumber').val("");
        //$('#Atitle').val("");
        $('#searchType').val(99);

        createTable(1);
    }

</script>