Letter/Controllers/PackageCaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using DAL;
using System.Linq.Expressions;

namespace Letter.Controllers
{
    public class PackageCaseController : BaseController
    {
        public ActionResult PackageCaseList()
        {
            return View();
        }

        public ActionResult PackageCaseDetail()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetPackageCase(int pageindex, int pagesize)
        {
            string expression = Power();
            var sql = "select * from [dbo].[t_CaseInfo] where IsDelete = 0" + expression;
            var resultModel = db.Database.SqlQuery<PackageCaseInfoModel>(sql)
                .OrderByDescending(n=>n.ID)
                              .Skip(pagesize * (pageindex - 1))
                              .Take(pagesize).ToList();
            #region
            foreach (var item in resultModel)
            {
                var packageInfo = db.t_PackageCasePersonnel.OrderByDescending(r => r.ID).FirstOrDefault(r => r.CaseInfoID == item.ID);
                if (packageInfo != null)
                {
                    if (packageInfo.PrefectureLeaderName == null)
                    {
                        item.PrefectureLeaderName = "未设置";
                    }
                    else
                    {
                        item.PrefectureLeaderName = packageInfo.PrefectureLeaderName;
                        item.PrefectureLeaderPosition = packageInfo.PrefectureLeaderPosition;
                    }
                    if (packageInfo.OfficeLeaderName == null)
                    {
                        item.OfficeLeaderName = "未设置";
                    }
                    else
                    {
                        item.OfficeLeaderName = packageInfo.OfficeLeaderName;
                        item.OfficeLeaderPosition = packageInfo.OfficeLeaderPosition;
                    }
                    
                    if (packageInfo.OfficeDirectLeaderName == null)
                    {
                        item.OfficeDirectLeaderName = "未设置";
                    }
                    else
                    {
                        item.OfficeDirectLeaderName = packageInfo.OfficeDirectLeaderName;
                        item.OfficeDirectLeaderPosition = packageInfo.OfficeDirectLeaderPosition;
                    }
                    
                    if (packageInfo.DirectLeaderName == null)
                    {
                        item.DirectLeaderName = "未设置";
                    }
                    else
                    {
                        item.DirectLeaderName = packageInfo.DirectLeaderName;
                        item.DirectLeaderPosition = packageInfo.DirectLeaderPosition;
                    }
                    if (packageInfo.StabilityLeaderName == null)
                    {
                        item.StabilityLeaderName = "未设置";
                    }
                    else
                    {
                        item.StabilityLeaderName = packageInfo.StabilityLeaderName;
                        item.StabilityLeaderPosition = packageInfo.StabilityLeaderPosition;
                    }
                    if (packageInfo.BasicLeaderName == null)
                    {
                        item.BasicLeaderName = "未设置";
                    }
                    else
                    {
                        item.BasicLeaderName = packageInfo.BasicLeaderName;
                        item.BasicLeaderPosition = packageInfo.BasicLeaderPosition;
                    }
                    if (packageInfo.BasicPoliceName == null)
                    {
                        item.BasicPoliceName = "未设置";
                    }
                    else
                    {
                        item.BasicPoliceName = packageInfo.BasicPoliceName;
                        item.BasicPolicePosition = packageInfo.BasicPolicePosition;
                    }
                }
                else
                {
                    item.PrefectureLeaderName = "未设置";
                    item.OfficeLeaderName = "未设置";
                    item.OfficeDirectLeaderName = "未设置";
                    item.DirectLeaderName = "未设置";
                    item.StabilityLeaderName = "未设置";
                    item.BasicLeaderName = "未设置";
                    item.BasicPoliceName = "未设置";
                }

            }
            #endregion

            ViewData["roleList"] = Power(1);
            ViewData["total"] = db.Database.SqlQuery<PackageCaseInfoModel>(sql).Count();
            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("PackageCasePartial", resultModel);
        }

        [HttpPost]
        public ActionResult QueryPackageCase(int pageindex, int pagesize, string AppealNumber, string AppealTitle,string PetitionName)
        {
            string expression = Power();
            string where = "";
            if (PetitionName.Trim() != "")
            {
                where += " and PetitionName like '%" + PetitionName.Trim() + "%'";
            }
            var sql = db.Database.SqlQuery<PackageCaseInfoModel>("select * from [dbo].[t_CaseInfo] where IsDelete = 0 " + where+ expression );
            var resultModel = sql.OrderByDescending(n => n.ID).Skip(pagesize * (pageindex - 1)).Take(pagesize).ToList();

            #region
            foreach (var item in resultModel)
            {
                var packageInfo = db.t_PackageCasePersonnel.OrderByDescending(r => r.ID).FirstOrDefault(r => r.CaseInfoID == item.ID);
                if (packageInfo != null)
                {
                    if (packageInfo.PrefectureLeaderName == null)
                    {
                        item.PrefectureLeaderName = "未设置";
                    }
                    else
                    {
                        item.PrefectureLeaderName = packageInfo.PrefectureLeaderName;
                        item.PrefectureLeaderPosition = packageInfo.PrefectureLeaderPosition;
                    }
                    if (packageInfo.OfficeLeaderName == null)
                    {
                        item.OfficeLeaderName = "未设置";
                    }
                    else
                    {
                        item.OfficeLeaderName = packageInfo.OfficeLeaderName;
                        item.OfficeLeaderPosition = packageInfo.OfficeLeaderPosition;
                    }

                    if (packageInfo.OfficeDirectLeaderName == null)
                    {
                        item.OfficeDirectLeaderName = "未设置";
                    }
                    else
                    {
                        item.OfficeDirectLeaderName = packageInfo.OfficeDirectLeaderName;
                        item.OfficeDirectLeaderPosition = packageInfo.OfficeDirectLeaderPosition;
                    }

                    if (packageInfo.DirectLeaderName == null)
                    {
                        item.DirectLeaderName = "未设置";
                    }
                    else
                    {
                        item.DirectLeaderName = packageInfo.DirectLeaderName;
                        item.DirectLeaderPosition = packageInfo.DirectLeaderPosition;
                    }
                    if (packageInfo.StabilityLeaderName == null)
                    {
                        item.StabilityLeaderName = "未设置";
                    }
                    else
                    {
                        item.StabilityLeaderName = packageInfo.StabilityLeaderName;
                        item.StabilityLeaderPosition = packageInfo.StabilityLeaderPosition;
                    }
                    if (packageInfo.BasicLeaderName == null)
                    {
                        item.BasicLeaderName = "未设置";
                    }
                    else
                    {
                        item.BasicLeaderName = packageInfo.BasicLeaderName;
                        item.BasicLeaderPosition = packageInfo.BasicLeaderPosition;
                    }
                    if (packageInfo.BasicPoliceName == null)
                    {
                        item.BasicPoliceName = "未设置";
                    }
                    else
                    {
                        item.BasicPoliceName = packageInfo.BasicPoliceName;
                        item.BasicPolicePosition = packageInfo.BasicPolicePosition;
                    }
                }
                else
                {
                    item.PrefectureLeaderName = "未设置";
                    item.OfficeLeaderName = "未设置";
                    item.OfficeDirectLeaderName = "未设置";
                    item.DirectLeaderName = "未设置";
                    item.StabilityLeaderName = "未设置";
                    item.BasicLeaderName = "未设置";
                    item.BasicPoliceName = "未设置";
                }

            }
            #endregion
            ViewData["roleList"] = Power(1);
            ViewData["total"] = sql.Count();
            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("PackageCasePartial", resultModel);
        }

        public ActionResult AddPackageCase()
        {
            return View();
        }

        /// <summary>
        /// 添加包案信息
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddPackageCase(PackageCasePersonnelModel model)
        {
            t_PackageCasePersonnel tbpersonnel = new t_PackageCasePersonnel();

Letter/Views/Shared/BergabeRecordPartial.cshtml
@model List<Model.BergabeModel>
@{
    int total = ViewData.GetInt("total");
    int pageindex = ViewData.GetInt("pageindex");
    int pagesize = ViewData.GetInt("pagesize");
    var currentUser = Session["CurrentUser"] as Model.t_User;
    var fileName = "";
    var downFile = "";
}
@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        if (@item[i].FileName != null)
        {
            var arr = @item[i].FileName.Split('_');
            var arrType = arr[arr.Length - 1].Split('.');
            fileName = arr[0] + "." + arrType[1];
            fileName = fileName.Remove(0, 1);
            fileName = fileName.Substring(0, fileName.Length - 1);
            downFile = @item[i].FileName.Remove(0, 1);
            downFile = downFile.Substring(0, downFile.Length - 1);
        }
        var role = @item[i].BergabeType == 0 ? "及时受理" : "按时答复";
        <tr>
            <th class="hidden">@item[i].ID</th>
            <th class="hidden">@item[i].AppealNumber</th>
            <th class="hidden">@item[i].TownshipType</th>
            <th class="hidden">@item[i].BergabeType</th>
            <td>@role</td>
            <td class="tdTit">@item[i].BergabeDate.ToString("yyyy-MM-dd")</td>
            <td class="tdstr"><p style="width: 100px;" class="textoverflow">@item[i].TransactDetails</td>
            <td class="tdstr"><p style="width: 100px;" class="textoverflow">@item[i].SurveyDetails</td>
            <td class="tdstr"><p style="width: 100px;" class="textoverflow">@item[i].DisposeDetails</td>
            @if(item[i].FileName != null)
            {
                 <td class="tdstr"><a href="~/UploadFile/@downFile" download="@downFile">@fileName</a></td>
            }
            else
            {
                <td class="tdstr">无</td>
            }
           <td>
               <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeModal(@(i+1))">查看</a>&nbsp;&nbsp;
               <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="EditModal(@(i + 1))">修改</a>&nbsp;&nbsp;
               <a href="javascript:void(0)" onclick="Del(@item[i].ID)">删除</a>
            </td>
        </tr>
    }
}
<tr class="hidden"><th id="total">@total</th></tr>

Letter/Views/Shared/CompanyPartial.cshtml
@model List<Model.t_Responsibility>
@{
    int total = ViewData.GetInt("total");
    int pageindex = ViewData.GetInt("pageindex");
    int pagesize = ViewData.GetInt("pagesize");
}

@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        var rowindex = ((@pageindex - 1) * @pagesize + i + 1);
        <tr>
            <th scope="row" class="hidden">@item[i].TableId</th>
            <th>@rowindex</th>
            <td>@item[i].UnitName</td>
            <td>
                <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="EditModal(@(i+1))">修改</a>&nbsp;&nbsp;
                <a href="javascript:void(0)" onclick="DelModal(@item[i].TableId)">删除</a>
            </td>
        </tr>
    }

}
<tr class="hidden"><th id="total">@total</th></tr>

Letter/Views/Shared/LeaderPartial.cshtml
@model List<Model.t_Leader>
@{
                /**/

                int total = ViewData.GetInt("total");
                int pageindex = ViewData.GetInt("pageindex");
                int pagesize = ViewData.GetInt("pagesize");
}
@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        var rowindex = ((@pageindex - 1) * @pagesize + i + 1);
        var Gender = @item[i].LeaderSex;
        var genderName = Gender == "1" ? "男" : "女";
        <tr>
            <th class="hidden">@item[i].LeaderId</th>
            <th class="hidden">@item[i].LeaderSex</th>
            <th>@rowindex</th>
            <td>@item[i].LeaderName</td>
            <td>@genderName</td>
            <td>@item[i].LeaderPosition</td>
            <td><p style="width: 150px;" class="textoverflow">@item[i].Remark</p></td>
            <td>
                <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="EditModal(@(i+1))">修改</a>&nbsp;&nbsp;
                @if (Session["CurrentUser"] != null)
                {
                    var currentUser = Session["CurrentUser"] as Model.t_User;
                    if (currentUser.UserRoleList.Contains("1") || currentUser.UserRoleList.Contains("2"))
                    {
                        <a href="javascript:void(0)" onclick="Del(@item[i].LeaderId)">删除</a>
                    }
                }
            </td>
        </tr>
    }

}
<tr class="hidden"><th id="total">@total</th></tr>

Letter/Views/Shared/LeaderReservationPartial.cshtml
@model List<Model.LeaderReservationModel>
@{
        int total = ViewData.GetInt("total");
        int pageindex = ViewData.GetInt("pageindex");
        int pagesize = ViewData.GetInt("pagesize");
      
}

@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        var rowindex = ((@pageindex - 1) * @pagesize + i + 1);
        var dateBefore = @item[i].ReceptionDateBefore == null ? "" : @item[i].ReceptionDateBefore.Value.ToString("yyyy-MM-dd");
        <tr>
            <th scope="row" class="hidden">@item[i].ID</th>
            <th class="hidden">@item[i].AppealTitle</th>
            <th class="hidden">@item[i].AppealContent</th>
            <th class="hidden">@item[i].ReceptionComment</th>
            <th class="hidden">@item[i].LeaderName (@item[i].LeaderPosition)</th>
            <th class="hidden">@item[i].ReceptionStatus</th>
            <th class="hidden">@item[i].ID</th>
            <td>@item[i].LeaderName</td>
            <td>@item[i].LeaderPosition</td>
            @*<td><p style="width: 120px;" class="textoverflow">@item[i].AppealTitle</p></td>*@
            <td>@item[i].PetitionName</td>
            <td>@dateBefore</td>
            <td>@item[i].ReceptionAddressBefore</td>
            <td>@item[i].ReceptionPersonBefore</td>
            <td><p style="width: 120px;" class="textoverflow">@item[i].ReceptionComment</td>
            @*@if (@item[i].ReceptionStatus == 0)
            {
                <td>预约中</td>
            }
            else if (@item[i].ReceptionStatus == 1)
            {
                <td>已完成</td>
            }
            else
            {
                <td>已取消</td>
            }*@

            <td>
                @*if (@item[i].ReceptionStatus == 0)
                {*@
                    @if (Session["CurrentUser"] != null)
                    {
                        var currentUser = Session["CurrentUser"] as Model.t_User;
                        if (currentUser.UserRoleList.Contains("1") || currentUser.UserRoleList.Contains("2") || currentUser.UserRoleList.Contains("3") || currentUser.UserRoleList.Contains("4"))
                        {
                            <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeModal(@(i+1))">查看</a>
                            <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="EditModal(@i+1)">修改</a>
                            @*<a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SaveModal(@i+1)">完成</a>*@
                            <a href="javascript:void(0)" onclick="Cancel(@item[i].ID)">删除</a>
                        }

                    }
                @*}*@
            </td>
        </tr>
    }
}

<tr class="hidden"><th id="total">@total</th></tr>

Letter/Views/Shared/LeaderReservationPartialOuter.cshtml
@model List<Model.LeaderReservationModel>
@{
    int total = ViewData.GetInt("total");
    int pageindex = ViewData.GetInt("pageindex");
    int pagesize = ViewData.GetInt("pagesize");
}

@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        var rowindex = ((@pageindex - 1) * @pagesize + i + 1);
        <tr>
            <td>@item[i].PetitionName</td>
            <td>@item[i].ID</td>
            @*@if (@item[i].ReceptionStatus == 0)
                {
                    <td>预约中</td>
                }
                else if (@item[i].ReceptionStatus == 1)
                {
                    <td>已完成</td>
                }
                else
                {
                    <td>已取消</td>
                }*@

            <td>
                @*if (@item[i].ReceptionStatus == 0)
                    {*@
                @if (Session["CurrentUser"] != null)
                    {
                        var currentUser = Session["CurrentUser"] as Model.t_User;
                        if (currentUser.UserRoleList.Contains("1") || currentUser.UserRoleList.Contains("2") || currentUser.UserRoleList.Contains("3") || currentUser.UserRoleList.Contains("4"))
                        {
                        <a href="javascript:;" onclick="detLink('@Url.Action("LeaderReservationList", new { name = item[i].PetitionName })')">约下访记录</a>
                    }

                }
                @*}*@
            </td>
        </tr>
    }
}

<tr class="hidden"><th id="total">@total</th></tr>

Letter/Views/Shared/MessagePartial.cshtml
<style>
    .message{
        font-style:normal
    }
</style>
@model List<Model.PackageCaseInfoModel>
    @{
        int total = ViewData.GetInt("total");
        int pageindex = ViewData.GetInt("pageindex");
        int pagesize = ViewData.GetInt("pagesize");
    }
    @if (Model != null && Model.Count > 0)
    {
        var item = Model;
        for (int i = 0; i < Model.Count; i++)
        {
            <li>
                <a href="@Url.Action("PackageCaseList", "PackageCase")">
                    <span >
                        <b>
                            @item[i].AppealTitle
                        </b>
                    </span>
                </a>
           </li>
         }
        <li>
            <div class="text-center">
                <a href="@Url.Action("PackageCaseList", "PackageCase")">查看更多</a>
            </div>
        </li>
    }
<input id="sumMessage" class="hidden" value="@total">

Letter/Views/Shared/PackageCasePartial.cshtml
@model List<Model.PackageCaseInfoModel>
@{
    int total = ViewData.GetInt("total");
    int pageindex = ViewData.GetInt("pageindex");
    int pagesize = ViewData.GetInt("pagesize");
    string roleList = ViewData.GetString("roleList") == "" ? "0" : ViewData.GetString("roleList");
    var currentUser = Session["CurrentUser"] as Model.t_User;
}

@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        <tr>
            <th scope="row" class="hidden">@item[i].ID</th>
            @*<td>@item[i].AppealNumber</td>
            <td>@item[i].AppealTitle</td>*@
            <td>@item[i].PetitionName</td>
            <td><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeName(1,@(i+1),'@item[i].PrefectureLeaderName','@item[i].PrefectureLeaderPosition','@roleList','@item[i].RelateUnitID','@currentUser.UserUnit')">@item[i].PrefectureLeaderName</a></td>
            <td><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeName(2,@(i+1),'@item[i].OfficeLeaderName','@item[i].OfficeLeaderPosition','@roleList','@item[i].RelateUnitID','@currentUser.UserUnit')">@item[i].OfficeLeaderName</a></td>

            <td><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeName(7,@(i+1),'@item[i].OfficeDirectLeaderName','@item[i].OfficeDirectLeaderPosition','@roleList','@item[i].RelateUnitID','@currentUser.UserUnit')">@item[i].OfficeDirectLeaderName</a></td>

            <td><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeName(3,@(i+1),'@item[i].DirectLeaderName','@item[i].DirectLeaderPosition','@roleList','@item[i].RelateAreaID','@currentUser.UserArea')">@item[i].DirectLeaderName</a></td>
            <td><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeName(4,@(i+1),'@item[i].StabilityLeaderName','@item[i].StabilityLeaderPosition','@roleList','@item[i].RelateAreaID','@currentUser.UserArea')">@item[i].StabilityLeaderName</a></td>
            <td><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeName(5,@(i+1),'@item[i].BasicLeaderName','@item[i].BasicLeaderPosition','@roleList','@item[i].RelateAreaID','@currentUser.UserArea')">@item[i].BasicLeaderName</a></td>
            <td><a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="SeeName(6,@(i+1),'@item[i].BasicPoliceName','@item[i].BasicPolicePosition','@roleList','@item[i].RelateAreaID','@currentUser.UserArea')">@item[i].BasicPoliceName</a></td>
            <td>
                <a href="javascript:void(0)" data-toggle="modal" data-target="#See-Modal" onclick="SeeModalTb(@item[i].ID)">查看</a>
            </td>

        </tr>
    }
}

<tr class="hidden"><th id="total">@total</th></tr>

Letter/Views/Shared/PackageModalPartial.cshtml
@model List<Model.t_PackageCaseRecord>
@{
    int pageindex = ViewData.GetInt("pageindex");
    int pagesize = ViewData.GetInt("pagesize");
}

@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        var Before = @item[i].BeforePosition;
        var BeforeName = Before == "" ? "无" : "" + "(" + @item[i].BeforePosition + ")" + "";

        var After = @item[i].AfterPosition;
        var AfterName = After == null ? "" : "" + "(" + @item[i].AfterPosition + ")" + "";
        var rowindex = ((@pageindex - 1) * @pagesize + i + 1);
        <tr>
            <th scope="row" style="display:none">@item[i].ID</th>
            <td>@item[i].BeforeName @BeforeName</td>
            <td>@item[i].AfterName @AfterName</td>
            <td>@item[i].UpdateDate.Value.ToString("yyyy-MM-dd")</td>
            <td>@item[i].UpdatePerson</td>
            <td>test</td>
            <td> 
                <a href="javascript:void(0)" data-toggle="modal" data-target="#See-Modal" onclick="SeeModalTb(@item[i].ID)">修改</a>
            </td>
        </tr>
    }
}
else
{
    <input class="hidden" id="total1" value="0" />
}

Letter/Views/Shared/SeeModalTb6.cshtml
@model List<Model.t_Bergabe>
<div class="pack-table">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>转送时限</th>
                <th>日期</th>
                <th>办理情况</th>
                <th>调查情况</th>
                <th>处理意见</th>
                <th>相关附件</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Count > 0)
            {
                var fileName = "";
                var downFile = "";
                var item = Model;
                for (int i = 0; i < Model.Count; i++)
                {
                    if(@item[i].FileName!= null)
                    {
                        var arr = @item[i].FileName.Split('_');
                        var arrType = arr[arr.Length - 1].Split('.');
                        fileName = arr[0] + "." + arrType[1];
                        fileName = fileName.Remove(0, 1);
                        fileName = fileName.Substring(0, fileName.Length - 1);
                        downFile = @item[i].FileName.Remove(0, 1);
                        downFile = downFile.Substring(0, downFile.Length - 1);
                    }


                    var role = @item[i].BergabeType == 0 ? "及时受理" : "按时答复";
                    <tr>
                        <td>@role</td>
                        <td class="tdTit">@item[i].BergabeDate.Value.ToString("yyyy-MM-dd")</td>
                        <td class="tdstr" title="@item[i].TransactDetails"><p style="width: 100px;" class="textoverflow">@item[i].TransactDetails</p></td>
                        <td class="tdstr" title="@item[i].SurveyDetails"><p style="width: 100px;" class="textoverflow">@item[i].SurveyDetails</p></td>
                        <td class="tdstr" title="@item[i].DisposeDetails"><p style="width: 100px;" class="textoverflow">@item[i].DisposeDetails</p></td>
                        @if (item[i].FileName != null)
                        {
                            <td><a href="~/UploadFile/@downFile" download="@downFile">@fileName</a></td>
                        }
                        else
                        {
                            <td>无</td>
                        }
                    </tr>
                }
            }
            else
            {
                 <tr>
                     <td colspan="6">暂无信息...</td>
                 </tr>
            }

        </tbody>
    </table>
</div>

Letter/Views/Shared/TransactPartial.cshtml
@model List<Model.CaseInfoModel>
@{
        int total = ViewData.GetInt("total");
        int pageindex = ViewData.GetInt("pageindex");
        int pagesize = ViewData.GetInt("pagesize");
}

@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        var rowindex = ((@pageindex - 1) * @pagesize + i + 1);
        <tr>
            <th scope="row" class="hidden">@item[i].ID</th>
            <td>@item[i].PetitionName</td>
            <td><p style="width: 120px;" class="textoverflow">@item[i].AppealContent</p></td>
            @if (item[i].IsStopPetition == 0)
            {
                <td>是</td>
            }
            else
            {
                <td>否</td>
            }

            @if (item[i].StopPetitionDate != null)
            {
                <td>@item[i].StopPetitionDate.Value.ToString("yyyy-MM-dd")</td>
            }
            else
            {
                <td>无</td>
            }

                <td>
                    <a href="javascript:void(0)" data-toggle="modal" data-target="#See-Modal" onclick="SeeModalTb(@item[i].ID)">查看</a>&nbsp;&nbsp;
                    <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="AddModal(@i+1)">办理</a>&nbsp;&nbsp;
                    <a href="javascript:void(0)"  onclick="detLink('@Url.Action("Letter", new { id = item[i].ID })')">办理记录</a>
                </td>
        </tr>
    }
}
<tr class="hidden"><th id="total">@total</th></tr>

Letter/Views/Shared/UpgradePartial.cshtml
@model List<Model.t_UpgradeList>
@{
    int total = ViewData.GetInt("total");
}
@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>@item[i].PetitionName</td>
            <td>@item[i].UnitName</td>
            <td>@item[i].CountyName</td>
            <td>@item[i].CountID</td>
            <td>
                <a href="javascript:void(0)" onclick="detLink('@Url.Action("UpgradeList", new { id = item[i].CaseInfoID})')">进京/赴省记录</a>
            </td>
        </tr>

    }


}
<tr class="hidden"><th id="total">@total</th></tr>